name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  pre-commit-checks:
    name: Pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - name: Install trivy
        run: |
          sudo wget https://github.com/aquasecurity/trivy/releases/download/v0.48.1/trivy_0.48.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.48.1_Linux-64bit.deb
      - name: Checkout
        uses: actions/checkout@v2
      - name: Terraform min/max versions
        id: minMax
        uses: clowdhaus/terraform-min-max@v1.0.4
      - name: Pre-commit Terraform ${{ steps.minMax.outputs.maxVersion }}
        uses: clowdhaus/terraform-composite-actions/pre-commit@v1.4.1
        with:
          terraform-version: ${{ steps.minMax.outputs.maxVersion }}
          terraform-docs-version: v0.17.0
  validate-examples:
    name: Validate examples
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: examples
    steps:
      - uses: hashicorp/setup-terraform@v1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check examples
        env:
          EXAMPLES: simple
        run: |
          for EXAMPLE in ${EXAMPLES}
          do
            echo "Validating $EXAMPLE"...
            cd $EXAMPLE && terraform init && terraform validate && cd -
          done
